---
# tasks file for users

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/group_module.html
- name: Create group infra-engineer
  group:
    name: infra-engineer
    state: present

- name: Create group sonar
  group:
    name:  sonar
    state: present    

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
- name: Create user ansible-user
  user:
    name: tunde 
    groups: 
    - infra-engineer 
    - www-data
    - sonar
    createhome: yes

- name: add sudoers file
  copy:
    src: ../files/tunde_sudoers
    dest: /etc/sudoers.d/tunde
    owner: root
    group: root
    mode: 0440

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
- name: Change file ownership, group and permissions
  file:
    path: /opt/sonarqube
    owner: tunde
    group: sonar
    mode: '0674'
