---
  - name: Install Packages
    apt:
      name: "{{ packages }}"
      state: present
    vars: 
      packages:
        - openjdk-11-jdk
        - openjdk-11-jre
        - python3-pip

# Install pyscorg dependecies for PostgreSQL
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
  - name: Install python package
    pip:
      name: psycopg2-binary