---
- name: Update and upgrade existing apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Utilities
  apt:
    name: "{{ packages }}"
    state: present 
  vars: 
    packages:
      - nano
      - vim
      - libapache2-mod-php
      - mariadb-client
      - php
      - php-curl
      - python3-pymysql
      - php-mysql
      - php-gd
      - php-ldap
      - php-zip
      - php-mbstring
      - php-xml
      - php-bcmath

- name: Installing Apache httpd, PHP, MariaDB and other requirements.
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - curl
      - git
      - unzip
  
  
# Checks if the director exists
- name: Check if destination directory exists
  vars:
    app_path: "/var/www/snipe-it"
  stat:
    path: "{{ app_path }}"
  register: app_stat



- name: Git checkout
  vars:
     app_path: "/var/www/snipe-it"
  git:
    repo: 'https://github.com/snipe/snipe-it.git'
    dest:  "{{ app_path }}"
  when: not app_stat.stat.exists
