---
# This playbook imports playbooks from sub-playbooks directory.
# Prod.yml is the root playbook

# - hosts: sonarqube
# - import_playbook: ../sub-playbooks/users.yml

# - hosts: all
# - import_playbook: ../sub-playbooks/packages.yml

# - hosts: web-db
# - import_playbook: ../sub-playbooks/database.yml

# - hosts: sonarqube
# - import_playbook: ../sub-playbooks/sonarqube.yml

# - hosts: web-db
# - import_playbook: ../sub-playbooks/apache.yml

- hosts: jenkins
- import_playbook: ../sub-playbooks/jenkins.yml