---
# This playbook imports playbooks from sub-playbooks directory.
# Prod.yml is the root playbook

# - hosts: snipeit
# - import_playbook: ../sub-playbooks/users.yml


# - hosts: snipeit
# - import_playbook: ../sub-playbooks/packages.yml

# - hosts: snipeit
# - import_playbook: ../sub-playbooks/database.yml


 - hosts: snipeit
 - import_playbook: ../sub-playbooks/sonarqube.yml


# - hosts: snipeit
# - import_playbook: ../sub-playbooks/apache.yml
