---

 - hosts: snipeit
 - import_playbook: ../sub-playbooks/users.yml


# - hosts: snipeit
# - import_playbook: ../sub-playbooks/packages.yml

# - hosts: snipeit
# - import_playbook: ../sub-playbooks/database.yml


# - hosts: snipeit
# - import_playbook: ../sub-playbooks/apache.yml
