pipeline {
    agent any

  stages {
    stage('GIT CHECKOUT') {
      steps {
        script {
          git "https://github.com/oxblixxx/snipe-it"
        }
      }
    }

    stage('Ansible run') {
      steps {
        script {
         ansiblePlaybook becomeUser: 'ubuntu', credentialsId: 'snipe-it', disableHostKeyChecking: true, installation: 'snipe-it', inventory: 'ansible/ubuntu/inventory', playbook: 'ansible/ubuntu/root-playbooks/prod.yml', sudoUser: null, vaultTmpPath: ''
        }
      }
    }
    }
}
