pipeline {
    agent any

  stages {
    stage('GIT CHECKOUT') {
      steps {
        script {
          
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }
    }
}
