pipeline {
    agent any

  stages {
    stage('GIT CHECKOUT') {
      steps {
        script {
          git "https://github.com/oxblixxx/snipe-it"
        }
      }
    }

    stage('Test') {
      steps {
        script {
          ansiblePlaybook credentialsId: 'web-server', disableHostKeyChecking: true, installation: 'snipe-it', inventory: 'ansible/ubuntu/inventory', playbook: 'ansible/ubuntu/root-playbooks/prod.yml', vaultTmpPath: ''
        }
      }
    }
    }
}
