---
- name: Set up all server
  hosts: all
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  vars:
    app_path: "/var/www/snipeit"
    fqdn: "localhost"
  tasks:
    - name: Update and upgrade existing apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
    - name: Install Utilities
      become: true          
      apt:
        name: "{{ packages }}"
        state: present 
      vars: 
        packages:
          - nano
          - vim
    - name: Installing Apache httpd, PHP, MariaDB and other requirements.
      become: true
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - mariadb-client
          - php
          - php-curl
          - php-mysql
          - php-gd
          - php-ldap
          - php-zip
          - php-mbstring
          - php-xml
          - php-bcmath
          - curl
          - git
          - unzip
          - python-pymysql
    #
